# Generated by Django 6.0.7 on 2026-07-15 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('ELETRICA', 'Elétrica'), ('HIDRAULICA', 'Hidráulica'), ('PINTURA', 'Pintura'), ('LIMPEZA', 'Limpeza'), ('OUTROS', 'Outros')], max_length=15)),
                ('cidade', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('CONCLUIDA', 'Concluída')], default='ABERTA', max_length=10)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
